name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Build and deploy
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        npm install # Opcional: si necesitas instalar dependencias
        npm run build # Opcional: si necesitas generar el sitio estático
        git checkout gh-pages # Cambia a la rama gh-pages o crea una nueva rama si es necesario
        cp -r dist/* . # Copia los archivos generados al directorio raíz
        git add .
        git commit -m "Deployed via GitHub Actions"
        git push origin gh-pages
